---
- hosts: all
  become: true
  vars:
    selinux_state: disabled

  roles:
    - role: geerlingguy.repo-epel
      tags: repo-epel
    - role: robertdebock.selinux
      tags: selinux
    - role: robertdebock.locale
      tags: locale
    - role: timezone
      tags: timezone
    - role: httpd
      tags: httpd
    - role: mamono210.ruby
      tags: ruby
    - role: postgresql
      tags: postgresql
    - role: redmine/create-pg-account-and-database
      tags: database
    - role: redmine/install
      tags: redmine
    - role: passenger
      tags: passenger
